
server:
  port: 8082
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "1.0"

cards:
 message: "welcome to loans microservice"
 cardsContactDetails:
   name: "Deepanshu"
   email: "deepanshu@gmail.com"
 onCallSupport:
   - "1234567890"
   - "9876543210"
