server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
#    active:
     active: git
  cloud:
    config:
      server:
#        native:
#          search-locations: "classpath:/config"
        git:
          uri: https://github.com/Deep5656/eazybytes-config.git
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
encrypt:
  key: "123DEJKYOLSFT345678901234567892"